
#map ctrl+shift+c command_palette


# BEGIN_KITTY_FONTS
font_family      family="SauceCodePro Nerd Font Mono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0
# END_KITTY_FONTS

editor nvim

# Change the tab style to powerline (others: fade, hidden, slant, custom)
tab_bar_style powerline
# Show tabs at the top
tab_bar_edge   top

# Configure powerline shape (slanted, angled, or rounded)
tab_powerline_style slanted

# Optional: Set beautiful active/inactive colors to match your theme
# active_tab_foreground   #000000
# active_tab_background   #a6e3a1
active_tab_font_style   bold
# inactive_tab_foreground #45475a
# inactive_tab_background #181825
# tab_bar_background      #11111b

# Trail
# How many milliseconds after the movement trigger should the animation
# be started. Set some small value here so that the animatation does not
# trigger during fast UI updates
cursor_trail 50
# How long the trail lasts in seconds. The secon value should be >= first
cursor_trail_decay 0.1 0.4
# Min number of cells the cursor must move before the trail is started
cursor_trail_threshold 2


# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME